### ISSUE TITLE
Change Parse Mode

### ISSUE THREAD

**Issue by azhe403** [Cyrus-Sushiant/Serilog.Sinks.TelegramBot#3]
How to change **parse_mode** instead of default `markdown` ?

**Comment by Cyrus-Sushiant** [comment]
You can get the last version (1.0.7) and you should set parse_mode to TelegramBot method.
`var log = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .WriteTo.TelegramBot("000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "000000", "Example", parseMode: ParseMode.HTML)
                .CreateLogger();`
